version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    env_file: ./.env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    image: dashafedorova/foodgram_backend
    env_file: ./.env
    volumes:
      - static:/backend_static
      - media:/media
    depends_on:
      - db
  frontend:
    image: dashafedorova/foodgram_frontend
    volumes:
      - ./frontend/:/app/result_build/
  nginx:
    image: nginx:1.19.3
    ports:
      - 8000:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/build:/usr/share/nginx/html/
      - ./docs/:/usr/share/nginx/html/api/docs/
      - static:/staticfiles/
      - media:/media

# version: '3'

# volumes:
#   pg_data:
#   static:
#   media:
#   static_frontend:

# services:
#   db:
#     image: postgres:13
#     env_file: ./.env
#     volumes:
#       - pg_data:/var/lib/postgresql/data

#   backend:
#     image: dashafedorova/foodgram_backend
#     env_file: ./.env
#     volumes:
#       - static:/backend_static
#       - media:/media
#     ports:
#       - 8000:8000
#     depends_on:
#       - db

#   frontend:
#     image: dashafedorova/foodgram_frontend
#     volumes:
#       - static_frontend/:/app/result_build/

#   nginx:
#     image: nginx:1.19.3
#     ports:
#       - 8000:80
#     volumes:
#       - ./nginx.conf:/etc/nginx/conf.d/default.conf
#       - static_frontend:/static_frontend/
#       - ./docs/:/usr/share/nginx/html/api/docs/
#       - static:/staticfiles/
#       - media:/media
#     depends_on:
#       - backend
