# Generated by Django 3.2.16 on 2023-11-17 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20231116_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='favorites',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='recipes.recipe', verbose_name='Избранное'),
        ),
    ]
