# Generated by Django 3.2.16 on 2023-11-24 20:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20231120_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='subscriptions',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='Подписки'),
        ),
    ]
