# Generated by Django 3.2.16 on 2023-11-24 20:47

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_subscription_subscriptions'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.CheckConstraint(check=models.Q(('subscriber__exact', django.db.models.expressions.F('subscriptions')), _negated=True), name='check_subscribe_to_yourself'),
        ),
    ]
